#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Require two arguments
if [ -z $2 ]; then
  echo "usage: $0 host interface"
  exit 1
fi

host=$1
iface=$2
host_iface=$host-$iface
file=${host_iface}.pcap

set -e

echo "*** Starting tcpdump on ${host}... Ctrl-c to stop capture"
echo "*** Pcap file will be written in ngsdn-tutorial/tmp/${file}"
docker exec -it mininet /mininet/host-cmd $host tcpdump -i $host_iface -w /tmp/"${file}"

if [ -x "$(command -v wireshark)" ]; then
  echo "*** Opening wireshark... Ctrl-c to quit"
  wireshark "${DIR}/../tmp/${file}"
fi